name: ci
on: push
jobs:
  django-test-job:
    runs-on: ubuntu-latest

    services: # job内で使用するサービス
      db:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
        options: >- # mysqlの起動チェック
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    container: # ここで指定したコンテナ内で作業する
      image: python:3
      ports:
        - 8000:8000
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: db
        DB_PORT: 3306
        TRUSTED_ORIGINS: ${{ secrets.TRUSTED_ORIGINS }}
        JWT_ALGORITHM: ${{ secrets.JWT_ALGORITHM }}
        JWT_AUTH_HEADER_TYPES: ${{ secrets.JWT_AUTH_HEADER_TYPES }}
    
    steps: 
      - uses: actions/checkout@v4 #レポジトリ内のコードにアクセスできるようにする
      
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        working-directory: ./django/src
        run:  |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test django
        working-directory: ./django/src/django_accounts
        run: python3 ./manage.py test

  nextjs-test-job:
    runs-on: ubuntu-latest

    container: # ここで指定したコンテナ内で作業する
      image: node:21-alpine
      ports:
        - 3000:3000
      env:
        NEXT_PUBLIC_API_ORIGIN: ${{ secrets.NEXT_PUBLIC_API_ORIGIN }}
    
    steps: 
      - uses: actions/checkout@v4 #レポジトリ内のコードにアクセスできるようにする

      - name: Cache yarn
        uses: actions/cache@v3
        with:
          path: |
            .yarn/cache
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        working-directory: ./nextjs/src/nextjs_accounts
        run: yarn install

      - name: Test nextjs
        working-directory: ./nextjs/src/nextjs_accounts
        run: yarn test